### ISSUE TITLE
Default to getting the latest mill version

### ISSUE THREAD

**Issue by jeantil** [lefou/millw#1]
The latest mill version can be computed by an HTTP call to 
`HEAD https://github.com/lihaoyi/mill/releases/latest`
In the response headers you will get a `Location` header which includes the latest version number such as: 
`Location: https://github.com/lihaoyi/mill/releases/tag/0.3.6`

In order to avoid waiting repeatedly on the network when the network is really bad, you could check for the existence of `${HOME}/.mill/latest` 
if it doesn't exist make a blocking (long timeouts) call and wait for the location information 
if it does exist use the version in `${HOME}/.mill/latest` AND make the call in the background with short timeouts (1second) in order to avoid piling http requests in the background.

a long call could look like 
```
curl -s -i -f -I https://github.com/lihaoyi/mill/releases/latest  | grep Location
```
while a short background call would be 
```
LANG=C curl -s -i -f -m $(echo "scale=3; 1/3" | bc) -I https://github.com/lihaoyi/mill/releases/latest  | grep Location
```
This will use a timeout of 333ms (0.333s), the `LANG=C` part is needed because bc only uses the dot (`.`) as decimal separator while curl will parse the number depending on the decimal format of the locale for the shell it runs in...

**Comment by lefou** [comment]
I really like the idea, but have currently no time to implement and test it. Any help would be very appreciated.

**Comment by jeantil** [comment]
@lefou looks like you went ahead and did this before I could address it :)

**Comment by lefou** [comment]
If you want, you can take the BAT file. ;-)
