### ISSUE TITLE
Doesn't work on macOS if .mill-version isn't found

### ISSUE THREAD

**Issue by nornagon** [lefou/millw#15]
When running on macOS 10.15.7:

```
touch: illegal option -- d
usage:
touch [-A [-][[hh]mm]SS] [-acfhm] [-r file] [-t [[CC]YY]MMDDhhmm[.SS]] file ...
```

**Comment by lefou** [comment]
Thanks for reporting. I assume, it's the following if condition statement from line 39 which won't work, which I assumed to be pretty standard:

```sh
  if [ -f ".mill-version" ] ; then
```

Do you have by any chance any documentation of the `if` on your macOS 10.15.6?

Until now I always referred to `man test` to see what is a valid if-condition, as that is what is used in `bash`. Could you please post the output of `man test` on your system?

**Comment by nornagon** [comment]
I think it's the `touch` invocation that's wrong. `-D` isn't supported by BSD touch.

**Comment by lefou** [comment]
Oh yes, I must really have used my mind in low-energy-mode that I came to my other conclusion.

**Comment by lefou** [comment]
@nornagon Could you apply and test to following change for me?

```diff
diff --git a/millw b/millw
index dedcedf..ff85903 100755
--- a/millw
+++ b/millw
@@ -54,7 +54,11 @@ if [ "x${MILL_VERSION}" = "x" ] ; then
   echo "You should provide a version via '.mill-version' file or --mill-version option."
 
   mkdir -p "${MILL_DOWNLOAD_PATH}"
-  LANG=C touch -d '1 hour ago' "${MILL_DOWNLOAD_PATH}/.expire_latest"
+  LANG=C touch -d '1 hour ago' "${MILL_DOWNLOAD_PATH}/.expire_latest" || (
+    # we might be OSX or BSD which don't have -d option for touch
+    # but probably a -A [-][[hh]mm]SS
+    touch "${MILL_DOWNLOAD_PATH}/.expire_latest"; touch -A -010000 "${MILL_DOWNLOAD_PATH}/.expire_latest"
+  )
   if [ "${MILL_DOWNLOAD_PATH}/.latest" -nt "${MILL_DOWNLOAD_PATH}/.expire_latest" ] ; then
     # we know a current latest version
     MILL_VERSION="$(head -n 1 ${MILL_DOWNLOAD_PATH}/.latest 2> /dev/null)"
```

**Comment by lefou** [comment]
@nornagon, thanks for checking. I can add the error message suppression to #16.
