### ISSUE TITLE
Unable to download `0.9.8-24-5fc810`

### ISSUE THREAD

**Issue by ckipp01** [lefou/millw#23]
Using the latest millw I'm unable to download the following version: `0.9.8-24-5fc810`. From looking at the script and echo'ing some stuff out it looks like the `MILL_VERSION_TAG` is capturing too much. For example the artifact I'm searching for is in `0.9.8/0.9.8-24-5fc810`, but it ends up looking in `0.9.8-24-5fc810/0.9.8-24-5fc810`.

**Comment by lefou** [comment]
I'm quite a bit pressure, timewise. If anybody will come up with a fix, that would be very appreciated.
