### ISSUE TITLE
For windows use an alternative to bitsadmin. 

### ISSUE THREAD

**Issue by DamianReeves** [lefou/millw#37]
Its been brought to my attention that launching mill using bitsadmin on windows is being flagged in the enterprise for security reasons. It would be great if an alternative was used.

**Comment by lefou** [comment]
`bitsadmin` is only used, if there is no working curl, otherwise curl is used. I think curl is nowadays present on Windows. Also, if bitsadmin is a security issue, why don't enterprise admins disable or uninstall it, rather than hoping, that nobody is using it. 🤔

**Comment by lefou** [comment]
* See also #14, which already provides a alternative based on powershell. Pull requests are wellcome.

**Comment by lefou** [comment]
`millw` is now integrated into the [official Mill project](https://github.com/com-lihaoyi/mill). If you find this issue is still relevant, please open a new issue there.
