### ISSUE TITLE
[Feature Request] Use `wget` when `curl` is not available

### ISSUE THREAD

**Issue by lolgab** [lefou/millw#39]
A little quality of life improvement would be to support `wget` as an alternative to `curl`.
This is especially useful when building Docker images in alpine containers (which include `wget` but not `curl`) so you don't need to install curl to run `millw`

**Comment by lefou** [comment]
Yeah, makes sense.

**Comment by lefou** [comment]
`millw` is now integrated into the [official Mill project](https://github.com/com-lihaoyi/mill). If you find this issue is still relevant, please open a new issue there.
